\C CTD;

DROP TABLE IF EXISTS Groups CASCADE;
DROP TABLE IF EXISTS Students CASCADE;
DROP TABLE IF EXISTS Courses CASCADE;
DROP TABLE IF EXISTS Lecturers CASCADE;
DROP TABLE IF EXISTS Marks CASCADE;
DROP TABLE IF EXISTS Plan CASCADE;
DROP TYPE IF EXISTS Mark;